apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
      listen 80;
      index index.php index.html index.htm;
      root /usr/share/nginx/html ;

    location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_pass http://go-service:8000;
       }
    }
  nginx.index: |
    <html>
    <body>
    <h1>Code.education Rocks</h1>
    </body>
    </html>