apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: devops6-go

spec:
  maxReplicas: 6
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops6-go
  targetCPUUtilizationPercentage: 15